# Creating MLflow deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codification-api
  template:
    metadata:
      labels:
        app: codification-api
    spec:
      containers:
        - name: api
          image: 467072721756.dkr.ecr.us-east-1.amazonaws.com/primepredict:1.1
          imagePullPolicy: Always
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://ec2-3-216-23-113.compute-1.amazonaws.com:5000
            - name: MLFLOW_MODEL_FREQ_NAME
              value: model_freq
            - name: MLFLOW_MODEL_FREQ_VERSION
              value: "2"
            - name: MLFLOW_MODEL_REG_NAME
              value: model_reg
            - name: MLFLOW_MODEL_REG_VERSION
              value: "2"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
